version: '5'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        ports:
            - "9200:9200"
#        networks:
#            - elastic
        volumes:
            - esdata:/usr/share/elasticsearch/data

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: "Ehsan"
            MYSQL_DATABASE: "store_db"
            MYSQL_USER: "Ehsan"
            MYSQL_PASSWORD: "Ehsan"
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql


    phpmyadmin:
       image: phpmyadmin/phpmyadmin
       links:
         - mysql:db
       ports:
         - "8080:80"
       environment:
         PMA_ARBITRARY: 1
    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.0
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
networks:
    elastic:
        driver: bridge

volumes:
    esdata:
        driver: local
    mysql-data:
        driver: local
